Github Auth works
maefranco/toro-net pull request #1
Opened 2017-10-20 08:06 UTC by gmofeng

Created my own credentials for Github Auth, so it saved my info and showed it on portal at my end.

2017-10-20 21:40 UTC, maefranco requested changes
I noticed that line 21 of your package.json has an updated version of nodemon. I don't think it will cause problems, but to play it safe, please change it back to the previous version.Then resubmit the pull request and I can approve

2017-10-21 10:07 UTC, gmofeng commented
nodemon version issue fixed

2017-10-21 10:08 UTC, gmofeng commented
nodemon version issue fixed

2017-10-21 20:00 UTC, maefranco approved these changes

2017-10-21 20:01 UTC, merged